"""agrega columna activa en usuarios

Revision ID: 3cb531676079
Revises: bb4dc4a7939b
Create Date: 2026-09-25 18:42:56.705835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb531676079'
down_revision: Union[str, Sequence[str], None] = 'bb4dc4a7939b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('activo', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'activo')
    # ### end Alembic commands ###